Added workflow to package and ship scrape2md to npm
tarasglek/scrape2md pull request #1
Opened 2024-02-16 21:16 UTC by Rachit1313

2024-02-16 21:18 UTC, Rachit1313 commented
@tarasglek , Could you please setup NPM_TOKEN in the repo's secret, create a release and also review this PR?

2024-02-16 21:21 UTC, humphd requested changes

2024-02-16 21:21 UTC, humphd commented on .github/workflows/npm-publish.yml
> +          node-version: '18'
Node 20 please

2024-02-16 21:21 UTC, humphd commented on .github/workflows/npm-publish.yml
> +      - name: Install pnpm
use the pnpm action:

```yaml
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
```

2024-02-16 21:21 UTC, humphd commented on package.json
> +  "main": "./src/index.ts",
You need to build this to JS.  I would recommend looking at what Yumei did with the other Typescript2Openai repo.

2024-02-18 15:23 UTC, tarasglek commented
<img width="812" alt="image" src="https://github.com/tarasglek/scrape2md-old/assets/857083/04b144d7-8cae-4bc4-8b4b-f14cdc4deae7">

2024-02-18 15:25 UTC, tarasglek approved these changes
lets try this

2024-02-18 15:30 UTC, merged